name: caloree_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.0

  flutter_bloc: ^9.1.1

  intl: ^0.20.2
  path_provider: ^2.1.5

  go_router: ^16.1.0

  get_it: ^8.2.0
  injectable: ^2.5.1
  freezed_annotation: ^3.1.0
  flutter_svg: ^2.2.0
  circular_reveal_animation: ^2.0.2
  image_picker: ^1.1.2
  fading_edge_scrollview: ^4.1.1
  json_annotation: ^4.9.0
  shared_preferences: ^2.5.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  solid_lints: ^0.3.1

  build_runner: ^2.4.15
  freezed: ^3.0.6
  go_router_builder: ^3.0.1
  injectable_generator: ^2.7.0
  flutter_gen_runner: ^5.11.0
  json_serializable: ^6.9.5

flutter:
  uses-material-design: true

  assets:
    - assets/images/
